export const mockProducts = [
  {
    id: "1",
    name: "Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation",
    price: 9999,
    quantity: 45,
    category: "Electronics",
    image: "/wireless-headphones.png",
    isActive: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "2",
    name: "USB-C Cable",
    description: "Durable USB-C charging cable with fast data transfer",
    price: 1599,
    quantity: 120,
    category: "Accessories",
    image: "/usb-cable.png",
    isActive: true,
    createdAt: new Date("2025-01-02"),
  },
  {
    id: "3",
    name: "Phone Stand",
    description: "Adjustable phone stand for desk and tabletop use",
    price: 2499,
    quantity: 0,
    category: "Accessories",
    image: "/phone-stand.jpg",
    isActive: false,
    createdAt: new Date("2025-01-03"),
  },
  {
    id: "4",
    name: "Laptop Bag",
    description: "Professional laptop bag with multiple compartments",
    price: 4999,
    quantity: 32,
    category: "Bags",
    image: "/laptop-bag.jpg",
    isActive: true,
    createdAt: new Date("2025-01-04"),
  },
  {
    id: "5",
    name: "Webcam 1080P",
    description: "Crystal clear 1080P webcam for streaming and video calls",
    price: 5999,
    quantity: 28,
    category: "Electronics",
    image: "/classic-webcam.png",
    isActive: true,
    createdAt: new Date("2025-01-05"),
  },
]

export const mockOrders = [
  {
    id: "01a8b9c2d3e4f5g6h7i8j9k0",
    userEmail: "john.doe@example.com",
    productName: "Wireless Headphones",
    quantity: 1,
    totalAmount: 9999,
    status: "DELIVERED",
    deliveryAddress: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    country: "USA",
    createdAt: new Date("2025-01-08"),
  },
  {
    id: "02b8c9d0e1f2g3h4i5j6k7l8",
    userEmail: "jane.smith@example.com",
    productName: "USB-C Cable",
    quantity: 3,
    totalAmount: 4797,
    status: "SHIPPED",
    deliveryAddress: "456 Oak Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90001",
    country: "USA",
    createdAt: new Date("2025-01-07"),
  },
  {
    id: "03c8d9e0f1g2h3i4j5k6l7m8",
    userEmail: "bob.wilson@example.com",
    productName: "Laptop Bag",
    quantity: 2,
    totalAmount: 9998,
    status: "PROCESSING",
    deliveryAddress: "789 Pine Rd",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    country: "USA",
    createdAt: new Date("2025-01-06"),
  },
  {
    id: "04d8e9f0g1h2i3j4k5l6m7n8",
    userEmail: "alice.johnson@example.com",
    productName: "Webcam 1080P",
    quantity: 1,
    totalAmount: 5999,
    status: "PAID",
    deliveryAddress: "321 Elm St",
    city: "Houston",
    state: "TX",
    zipCode: "77001",
    country: "USA",
    createdAt: new Date("2025-01-05"),
  },
  {
    id: "05e8f9g0h1i2j3k4l5m6n7o8",
    userEmail: "charlie.brown@example.com",
    productName: "Phone Stand",
    quantity: 2,
    totalAmount: 4998,
    status: "PENDING_PAYMENT",
    deliveryAddress: "654 Maple Dr",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85001",
    country: "USA",
    createdAt: new Date("2025-01-04"),
  },
  {
    id: "06f8g9h0i1j2k3l4m5n6o7p8",
    userEmail: "diana.prince@example.com",
    productName: "Wireless Headphones",
    quantity: 1,
    totalAmount: 9999,
    status: "CANCELLED",
    deliveryAddress: "987 Cedar Ln",
    city: "Philadelphia",
    state: "PA",
    zipCode: "19101",
    country: "USA",
    createdAt: new Date("2025-01-03"),
  },
  {
    id: "07g8h9i0j1k2l3m4n5o6p7q8",
    userEmail: "evan.turner@example.com",
    productName: "USB-C Cable",
    quantity: 5,
    totalAmount: 7995,
    status: "REFUNDED",
    deliveryAddress: "147 Birch Way",
    city: "San Antonio",
    state: "TX",
    zipCode: "78201",
    country: "USA",
    createdAt: new Date("2025-01-02"),
  },
]
